// ─────────────────────────────────────────────────────────────────────────────
// The St. Louis school registry.
//
// This file is the moat. Scores are commodity; knowing that "SLUH", "St. Louis
// U. High" and "St Louis University High School" are one school — and that
// "Lutheran North" and "Lutheran South" are not — is the part nobody else in
// this metro has written down.
//
// Aliases are added only when a real source was seen using them. Guessing new
// spellings into this file is how two schools eventually get merged.
// ─────────────────────────────────────────────────────────────────────────────

import type { School } from "../graph/types.ts";

type Gender = "boys" | "girls";

const mo = (
  id: string,
  name: string,
  shortName: string,
  city: string,
  aliases: string[],
  nickname?: string,
  genderContext?: Gender,
): School => ({ id, name, shortName, city, state: "MO", metro: "st-louis", aliases, nickname, genderContext });

const il = (
  id: string,
  name: string,
  shortName: string,
  city: string,
  aliases: string[],
  nickname?: string,
  genderContext?: Gender,
): School => ({ id, name, shortName, city, state: "IL", metro: "st-louis", aliases, nickname, genderContext });

export const ST_LOUIS_SCHOOLS: School[] = [
  // ── Private / parochial, Missouri side ────────────────────────────────────
  mo("sluh", "St. Louis University High School", "SLUH", "St. Louis",
    ["SLUH", "St. Louis U. High", "St Louis U High", "St. Louis University High", "St. Louis U High", "Saint Louis University High School", "St. Louis U. High School"], "Junior Billikens", "boys"),
  mo("cbc", "Christian Brothers College High School", "CBC", "Town and Country",
    ["CBC", "CBC High School", "Christian Brothers College", "Christian Bros College"], "Cadets", "boys"),
  mo("de-smet", "De Smet Jesuit High School", "De Smet", "Creve Coeur",
    ["De Smet", "DeSmet", "De Smet Jesuit", "DeSmet Jesuit", "De Smet Jesuit HS"], "Spartans", "boys"),
  mo("chaminade", "Chaminade College Preparatory School", "Chaminade", "Creve Coeur",
    ["Chaminade", "Chaminade College Prep", "Chaminade Prep"], "Red Devils", "boys"),
  mo("vianney", "St. John Vianney High School", "Vianney", "Kirkwood",
    ["Vianney", "St. John Vianney", "St John Vianney", "John Vianney"], "Golden Griffins", "boys"),
  mo("priory", "Saint Louis Priory School", "Priory", "Creve Coeur",
    ["Priory", "St. Louis Priory", "Saint Louis Priory", "MSA Priory"], "Rebels", "boys"),
  mo("micds", "Mary Institute and Saint Louis Country Day School", "MICDS", "Ladue",
    ["MICDS", "Mary Institute and St. Louis Country Day", "Country Day"], "Rams"),
  mo("jburroughs", "John Burroughs School", "John Burroughs", "Ladue",
    ["John Burroughs", "Burroughs", "John Burroughs School"], "Bombers"),
  mo("whitfield", "Whitfield School", "Whitfield", "Creve Coeur", ["Whitfield"], "Warriors"),
  mo("principia", "Principia School", "Principia", "Town and Country",
    ["Principia", "Principia Upper School"], "Panthers"),
  mo("westminster-christian", "Westminster Christian Academy", "Westminster Christian", "Town and Country",
    ["Westminster Christian Academy", "Westminster Christian", "WCA"], "Wildcats"),
  mo("lutheran-north", "Lutheran High School North", "Lutheran North", "St. Louis",
    ["Lutheran North", "Lutheran High North", "Lutheran High School North"], "Crusaders"),
  mo("lutheran-south", "Lutheran High School South", "Lutheran South", "St. Louis",
    ["Lutheran South", "Lutheran High South", "Lutheran High School South"], "Lancers"),
  mo("lutheran-st-charles", "Lutheran High School of St. Charles County", "Lutheran St. Charles", "St. Peters",
    ["Lutheran St. Charles", "Lutheran High St. Charles", "Lutheran St Charles County"], "Cougars"),
  mo("st-dominic", "St. Dominic High School", "St. Dominic", "O'Fallon",
    ["St. Dominic", "St Dominic", "St. Dominic Catholic High School", "Saint Dominic"], "Crusaders"),
  mo("duchesne", "Duchesne High School", "Duchesne", "St. Charles",
    ["Duchesne", "Duchesne HS"], "Pioneers"),
  mo("borgia", "St. Francis Borgia Regional High School", "Borgia", "Washington",
    ["Borgia", "St. Francis Borgia", "Borgia Regional", "St. Francis Borgia Regional"], "Knights"),
  mo("cor-jesu", "Cor Jesu Academy", "Cor Jesu", "Affton", ["Cor Jesu", "Cor Jesu Academy"], "Chargers", "girls"),
  mo("nerinx", "Nerinx Hall High School", "Nerinx Hall", "Webster Groves",
    ["Nerinx Hall", "Nerinx"], "Markers", "girls"),
  mo("visitation", "Visitation Academy", "Visitation", "Town and Country",
    ["Visitation", "Visitation Academy", "Viz"], "Vivettes", "girls"),
  mo("villa-duchesne", "Villa Duchesne", "Villa Duchesne", "Frontenac",
    ["Villa Duchesne", "Villa Duchesne / Oak Hill", "Villa"], "Saints", "girls"),
  mo("ursuline", "Ursuline Academy", "Ursuline", "Oakland", ["Ursuline", "Ursuline Academy"], "Bears", "girls"),
  mo("incarnate-word", "Incarnate Word Academy", "Incarnate Word", "Bel-Nor",
    ["Incarnate Word", "Incarnate Word Academy", "IWA"], "Red Knights", "girls"),
  mo("rosati-kain", "Rosati-Kain Academy", "Rosati-Kain", "St. Louis",
    ["Rosati-Kain", "Rosati Kain"], "Kougars", "girls"),
  mo("notre-dame", "Notre Dame High School", "Notre Dame", "Lemay", ["Notre Dame", "Notre Dame HS"], "Rebels"),
  mo("st-mary-s", "St. Mary's High School", "St. Mary's", "St. Louis",
    ["St. Mary's", "St Marys", "St. Mary's South Side", "Saint Mary's"], "Dragons", "boys"),
  mo("bishop-dubourg", "Bishop DuBourg High School", "Bishop DuBourg", "St. Louis",
    ["Bishop DuBourg", "DuBourg", "Bishop Dubourg"], "Cavaliers"),
  mo("trinity-catholic", "Trinity Catholic High School", "Trinity Catholic", "Spanish Lake",
    ["Trinity Catholic", "Trinity Catholic HS"], "Titans"),
  mo("lift-for-life", "Lift For Life Academy", "Lift For Life", "St. Louis",
    ["Lift for Life Academy", "Lift For Life", "Lift for Life"], "Hawks"),
  mo("barat", "Barat Academy", "Barat", "Dardenne Prairie", ["Barat Academy", "Barat"], "Eagles"),
  mo("tower-grove", "Tower Grove Christian", "Tower Grove Christian", "St. Louis",
    ["Tower Grove Christian", "Tower Grove Christian Academy"], "Eagles"),

  mo("cardinal-ritter", "Cardinal Ritter College Prep", "Cardinal Ritter", "St. Louis",
    ["Cardinal Ritter", "Cardinal Ritter College Prep", "Ritter"], "Lions"),
  mo("mica", "Miriam Academy", "Miriam", "St. Louis", ["Miriam Academy"], undefined),
  mo("crossroads", "Crossroads College Preparatory School", "Crossroads", "St. Louis",
    ["Crossroads College Prep", "Crossroads"], "Coyotes"),
  mo("new-haven", "New Haven High School", "New Haven", "New Haven", ["New Haven"], "Shamrocks"),
  mo("wright-city", "Wright City High School", "Wright City", "Wright City", ["Wright City"], "Wildcats"),
  mo("st-charles-borromeo", "St. Charles Borromeo", "Borromeo", "St. Charles", ["St. Charles Borromeo"], undefined),

  // ── Public, St. Louis County & City ───────────────────────────────────────
  mo("kirkwood", "Kirkwood High School", "Kirkwood", "Kirkwood", ["Kirkwood", "Kirkwood HS"], "Pioneers"),
  mo("webster-groves", "Webster Groves High School", "Webster Groves", "Webster Groves",
    ["Webster Groves", "Webster", "Webster Groves HS"], "Statesmen"),
  mo("ladue", "Ladue Horton Watkins High School", "Ladue", "Ladue",
    ["Ladue", "Ladue Horton Watkins", "Ladue HS"], "Rams"),
  mo("clayton", "Clayton High School", "Clayton", "Clayton", ["Clayton", "Clayton HS"], "Greyhounds"),
  mo("brentwood", "Brentwood High School", "Brentwood", "Brentwood", ["Brentwood"], "Eagles"),
  mo("maplewood-rh", "Maplewood Richmond Heights High School", "Maplewood RH", "Maplewood",
    ["Maplewood Richmond Heights", "Maplewood-Richmond Heights", "MRH"], "Blue Devils"),
  mo("university-city", "University City High School", "University City", "University City",
    ["University City", "U. City", "U City"], "Lions"),
  mo("normandy", "Normandy High School", "Normandy", "Normandy", ["Normandy"], "Vikings"),
  mo("riverview-gardens", "Riverview Gardens High School", "Riverview Gardens", "Riverview",
    ["Riverview Gardens", "Riverview"], "Rams"),
  mo("jennings", "Jennings High School", "Jennings", "Jennings", ["Jennings"], "Warriors"),
  mo("mccluer", "McCluer High School", "McCluer", "Florissant", ["McCluer"], "Comets"),
  mo("mccluer-north", "McCluer North High School", "McCluer North", "Florissant",
    ["McCluer North"], "Stars"),
  mo("hazelwood-central", "Hazelwood Central High School", "Hazelwood Central", "Florissant",
    ["Hazelwood Central"], "Hawks"),
  mo("hazelwood-east", "Hazelwood East High School", "Hazelwood East", "Spanish Lake",
    ["Hazelwood East"], "Spartans"),
  mo("hazelwood-west", "Hazelwood West High School", "Hazelwood West", "Hazelwood",
    ["Hazelwood West"], "Wildcats"),
  mo("pattonville", "Pattonville High School", "Pattonville", "Maryland Heights",
    ["Pattonville"], "Pirates"),
  mo("ritenour", "Ritenour High School", "Ritenour", "Overland", ["Ritenour"], "Huskies"),
  mo("parkway-central", "Parkway Central High School", "Parkway Central", "Chesterfield",
    ["Parkway Central"], "Colts"),
  mo("parkway-north", "Parkway North High School", "Parkway North", "Creve Coeur",
    ["Parkway North"], "Vikings"),
  mo("parkway-south", "Parkway South High School", "Parkway South", "Manchester",
    ["Parkway South"], "Patriots"),
  mo("parkway-west", "Parkway West High School", "Parkway West", "Ballwin", ["Parkway West"], "Longhorns"),
  mo("lafayette", "Lafayette High School", "Lafayette", "Wildwood",
    ["Lafayette", "Lafayette HS", "Lafayette (Wildwood)"], "Lancers"),
  mo("marquette", "Marquette High School", "Marquette", "Chesterfield",
    ["Marquette", "Marquette HS", "Marquette (Chesterfield)"], "Mustangs"),
  mo("eureka", "Eureka High School", "Eureka", "Eureka", ["Eureka", "Eureka HS"], "Wildcats"),
  mo("rockwood-summit", "Rockwood Summit High School", "Rockwood Summit", "Fenton",
    ["Rockwood Summit", "Summit"], "Falcons"),
  mo("lindbergh", "Lindbergh High School", "Lindbergh", "St. Louis", ["Lindbergh"], "Flyers"),
  mo("mehlville", "Mehlville High School", "Mehlville", "Oakville", ["Mehlville"], "Panthers"),
  mo("oakville", "Oakville High School", "Oakville", "Oakville", ["Oakville"], "Tigers"),
  mo("affton", "Affton High School", "Affton", "Affton", ["Affton"], "Cougars"),
  mo("bayless", "Bayless High School", "Bayless", "St. Louis", ["Bayless"], "Broncos"),
  mo("hancock", "Hancock High School", "Hancock", "Lemay", ["Hancock", "Hancock Place"], "Tigers"),
  mo("valley-park", "Valley Park High School", "Valley Park", "Valley Park", ["Valley Park"], "Hawks"),
  mo("fox", "Fox High School", "Fox", "Arnold", ["Fox", "Fox HS"], "Warriors"),
  mo("seckman", "Seckman High School", "Seckman", "Imperial", ["Seckman"], "Jaguars"),
  mo("northwest-cedar-hill", "Northwest High School", "Northwest", "Cedar Hill",
    ["Northwest", "Northwest Cedar Hill", "Northwest (Cedar Hill)"], "Lions"),
  mo("windsor", "Windsor High School", "Windsor", "Imperial", ["Windsor", "Windsor (Imperial)"], "Owls"),
  mo("de-soto", "De Soto High School", "De Soto", "De Soto", ["De Soto", "DeSoto"], "Dragons"),
  mo("festus", "Festus High School", "Festus", "Festus", ["Festus"], "Tigers"),
  mo("hillsboro", "Hillsboro High School", "Hillsboro", "Hillsboro", ["Hillsboro"], "Hawks"),
  mo("jefferson", "Jefferson High School", "Jefferson", "Festus", ["Jefferson", "Jefferson (Festus)"], "Blue Jays"),
  mo("herculaneum", "Herculaneum High School", "Herculaneum", "Herculaneum", ["Herculaneum"], "Blackcats"),
  mo("crystal-city", "Crystal City High School", "Crystal City", "Crystal City", ["Crystal City"], "Hornets"),
  mo("st-pius-x", "St. Pius X High School", "St. Pius X", "Festus", ["St. Pius X", "St Pius X", "St. Pius"], "Lancers"),

  // ── St. Charles County ────────────────────────────────────────────────────
  mo("francis-howell", "Francis Howell High School", "Francis Howell", "St. Charles",
    ["Francis Howell", "Francis Howell HS"], "Vikings"),
  mo("francis-howell-central", "Francis Howell Central High School", "Francis Howell Central", "Cottleville",
    ["Francis Howell Central", "FHC"], "Spartans"),
  mo("francis-howell-north", "Francis Howell North High School", "Francis Howell North", "St. Charles",
    ["Francis Howell North", "FHN"], "Knights"),
  mo("fort-zumwalt-north", "Fort Zumwalt North High School", "Fort Zumwalt North", "O'Fallon",
    ["Fort Zumwalt North", "Ft. Zumwalt North", "FZ North"], "Panthers"),
  mo("fort-zumwalt-south", "Fort Zumwalt South High School", "Fort Zumwalt South", "St. Peters",
    ["Fort Zumwalt South", "Ft. Zumwalt South", "FZ South"], "Bulldogs"),
  mo("fort-zumwalt-east", "Fort Zumwalt East High School", "Fort Zumwalt East", "St. Peters",
    ["Fort Zumwalt East", "Ft. Zumwalt East", "FZ East"], "Lions"),
  mo("fort-zumwalt-west", "Fort Zumwalt West High School", "Fort Zumwalt West", "O'Fallon",
    ["Fort Zumwalt West", "Ft. Zumwalt West", "FZ West"], "Jaguars"),
  mo("st-charles", "St. Charles High School", "St. Charles", "St. Charles",
    ["St. Charles", "St Charles High"], "Pirates"),
  mo("st-charles-west", "St. Charles West High School", "St. Charles West", "St. Charles",
    ["St. Charles West", "St Charles West"], "Warriors"),
  mo("orchard-farm", "Orchard Farm High School", "Orchard Farm", "St. Charles", ["Orchard Farm"], "Eagles"),
  mo("timberland", "Timberland High School", "Timberland", "Wentzville", ["Timberland"], "Wolves"),
  mo("liberty-wentzville", "Liberty High School", "Liberty", "Wentzville",
    ["Liberty", "Liberty (Wentzville)", "Wentzville Liberty"], "Eagles"),
  mo("holt", "Holt High School", "Holt", "Wentzville", ["Holt", "Wentzville Holt"], "Indians"),
  mo("north-point", "North Point High School", "North Point", "Wentzville", ["North Point"], "Grizzlies"),
  mo("howell-north", "Howell North", "Howell North", "St. Charles", ["Howell North"], undefined),
  mo("washington", "Washington High School", "Washington", "Washington", ["Washington", "Washington HS"], "Blue Jays"),
  mo("union", "Union High School", "Union", "Union", ["Union"], "Wildcats"),
  mo("pacific", "Pacific High School", "Pacific", "Pacific", ["Pacific"], "Indians"),
  mo("st-clair", "St. Clair High School", "St. Clair", "St. Clair", ["St. Clair", "St Clair"], "Bulldogs"),
  mo("sullivan", "Sullivan High School", "Sullivan", "Sullivan", ["Sullivan"], "Eagles"),
  mo("rockhurst", "Rockhurst High School", "Rockhurst", "Kansas City",
    ["Rockhurst", "Rockhurst High School"], "Hawklets", "boys"),

  // ── Illinois, Metro East ──────────────────────────────────────────────────
  il("belleville-east", "Belleville East High School", "Belleville East", "Belleville",
    ["Belleville East"], "Lancers"),
  il("belleville-west", "Belleville West High School", "Belleville West", "Belleville",
    ["Belleville West"], "Maroons"),
  il("edwardsville", "Edwardsville High School", "Edwardsville", "Edwardsville",
    ["Edwardsville", "Edwardsville HS"], "Tigers"),
  il("ofallon-il", "O'Fallon Township High School", "O'Fallon", "O'Fallon",
    ["O'Fallon", "OFallon Township", "O'Fallon Township"], "Panthers"),
  il("alton", "Alton High School", "Alton", "Alton", ["Alton", "Alton HS"], "Redbirds"),
  il("alton-marquette", "Marquette Catholic High School", "Alton Marquette", "Alton",
    ["Alton Marquette", "Marquette Catholic", "Marquette (Alton)"], "Explorers"),
  il("granite-city", "Granite City High School", "Granite City", "Granite City", ["Granite City"], "Warriors"),
  il("collinsville", "Collinsville High School", "Collinsville", "Collinsville", ["Collinsville"], "Kahoks"),
  il("east-st-louis", "East St. Louis Senior High School", "East St. Louis", "East St. Louis",
    ["East St. Louis", "East Side", "East St Louis"], "Flyers"),
  il("highland-il", "Highland High School", "Highland", "Highland", ["Highland", "Highland (IL)"], "Bulldogs"),
  il("triad", "Triad High School", "Triad", "Troy", ["Triad"], "Knights"),
  il("mascoutah", "Mascoutah High School", "Mascoutah", "Mascoutah", ["Mascoutah"], "Indians"),
  il("waterloo", "Waterloo High School", "Waterloo", "Waterloo", ["Waterloo"], "Bulldogs"),
  il("columbia-il", "Columbia High School", "Columbia", "Columbia", ["Columbia", "Columbia (IL)"], "Eagles"),
  il("freeburg", "Freeburg Community High School", "Freeburg", "Freeburg", ["Freeburg"], "Midgets"),
  il("breese-central", "Central Community High School", "Breese Central", "Breese",
    ["Breese Central", "Central (Breese)"], "Cougars"),
  il("cahokia", "Cahokia High School", "Cahokia", "Cahokia", ["Cahokia"], "Comanches"),
  il("roxana", "Roxana High School", "Roxana", "Roxana", ["Roxana"], "Shells"),
  il("jerseyville", "Jersey Community High School", "Jersey", "Jerseyville",
    ["Jersey", "Jersey Community", "Jerseyville"], "Panthers"),
  il("civic-memorial", "Civic Memorial High School", "Civic Memorial", "Bethalto",
    ["Civic Memorial", "CM"], "Eagles"),
  il("althoff", "Althoff Catholic High School", "Althoff", "Belleville",
    ["Althoff", "Althoff Catholic"], "Crusaders"),
];
